### ISSUE TITLE
Error in nonce check javascript

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2026]
Uncaught TypeError: c.ajax(...).success is not a function

**Comment by ducminhn** [comment]
I got the same issue on the latest version (1.5.7.1)

**Comment by Dj4y** [comment]
Hi guys ! I've got exactly the same problem, and i think it's why all my 'save as post type' pocessors don't work anymore.
I'm working with the latest version(1.5.7), and i think this problem occurred for the first time once i'd updated the 'caldera custom fields' plugin.

**Comment by tmdesigned** [comment]
Most likely you are using an updated version of jQuery, version 3 or later. WordPress currently (4.9) ships with jQuery 1.12.4 and it is generally bad practice to update core libraries. 

However, Caldera is relying on jQuery code that was deprecated in 1.8, and the replacement has been available since 1.5, which shipped with WordPress 3.2. I don't know how far back Caldera tries to support, but I have created a pull request to update the code in the hopes that they will change it to support those instances where jQuery must be updated for other libraries.

**Comment by Shelob9** [comment]
I am not sure that #2469, which will be merged once tested, will fix this.

#2460 will remove this feature that I believe is now counter-productive.

**Comment by Shelob9** [comment]
Should be fixed via #2460 / #2469
